Repository ginge/FreeRTOS-Pebble, pull requests merged in 2018-02, with the labels that each got.

#90 Use CCM Memory for storing FB, and some heaps
  Config/FreeRTOSConfig.h
  Utilities/space.sh
  hw/chip/stm32f4xx/startup_stm32f4xx.s
  hw/chip/stm32f4xx/stm32f4xx.lds
  hw/platform/snowy_family/platform_config_common.h
  hw/platform/snowy_family/snowy_display.c
  hw/platform/tintin/platform.h
  rcore/appmanager.c
  rcore/backlight.c
  rcore/buttons.c
Labels: PR-ready

#83 Fix ClickHandler context
  rcore/buttons.c
  rwatch/input/click_config.h
Labels: PR-ready

#84 Update README.md
  README.md
Labels: question

#91 debug: move to a special panic stack to save some max stack size
  rcore/debug.c
Labels: PR-ready

#89 Overlay window support
  config.mk
  hw/platform/snowy_family/platform_config_common.h
  rcore/appmanager.c
  rcore/appmanager.h
  rcore/appmanager_app_runloop.c
  rcore/overlay_manager.c
  rcore/overlay_manager.h
  rcore/rebbleos.c
  rwatch/ui/animation/animation.c
  rwatch/ui/window.c
  rwatch/ui/window.h
Labels: PR-reviewplz

#60 Implement Vibes API
  Apps/System/testapp.c
  Apps/System/tests/config.mk
  Apps/System/tests/test_defs.h
  Apps/System/tests/vibes_test.c
  config.mk
  rcore/api_func_symbols.h
  rwatch/ui/vibes.c
  rwatch/ui/vibes.h
Labels: PR-ready, help wanted
